# Generated by Django 5.0.14 on 2026-09-10 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('idagendamento', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Identificador')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome')),
                ('telefone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('servico', models.CharField(choices=[('corte', 'Corte de Cabelo'), ('barba', 'Barba'), ('combo', 'Combo Completo')], max_length=10, verbose_name='Servico')),
                ('data_agendamento', models.DateField(verbose_name='Data do Agendamento')),
                ('horario', models.TimeField(verbose_name='Horario Agendamento')),
            ],
        ),
    ]
