# Generated by Django 5.0.14 on 2026-09-03 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('idagendamento', models.BigIntegerField(primary_key=True, serialize=False, unique=True, verbose_name='Identificador')),
                ('data_agendamento', models.DateField(verbose_name='Data do Agendamento')),
                ('horario', models.TimeField(verbose_name='Horario Agendamento')),
                ('observacao', models.CharField(max_length=200, verbose_name='Observacao')),
                ('email', models.EmailField(max_length=150, unique=True, verbose_name='Email')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Valor')),
            ],
        ),
    ]
