# Generated by Django 5.0.14 on 2026-09-17 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='agendamento',
            unique_together={('barbeiro', 'data', 'horario')},
        ),
    ]
